### ISSUE TITLE
CUR_DIR return and working tree pollution in laminar job scripts

### ISSUE THREAD

**Issue by arunisaac** [genenetwork/genenetwork3#24]
The laminar job scripts `scripts/laminar/*.sh` all return to `CUR_DIR` in the
last line. Why is that necessary?

Also, I assume there is some checked out git working tree at `GN3_CI_DIR`. You
are running some command (pylint, mypy, unittest, etc.) in that working
tree. These commands might leave files behind, thus polluting the working
tree. So successive runs of the same job might see a different state of the
working tree even when there are no new commits.

It would be better to, after pulling, clone the repo from `GN3_CI_DIR` to
`CUR_DIR`, and then run the command (pylint, mypy, unittest, etc.) in this
cloned copy. On the default setting, laminar deletes the contents of `CUR_DIR`
after the job is done. The cloning is cheap since git tries to hard link when
possible. See documentation for option -l in the man page of `git clone`.

**Comment by BonfaceKilz** [comment]
Hi!

Arun Isaac ***@***.***> anaandika:

> The laminar job scripts `scripts/laminar/*.sh` all return to `CUR_DIR` in the
> last line. Why is that necessary?
>
Not really necessary. I was testing out the
laminar scripts on my local set-up; and somewhere
I had: `cd $GN3_CI_DIR`; so I wanted the script to
"reset" the directory once it completed running.

> Also, I assume there is some checked out git
> working tree at `GN3_CI_DIR`.

Yep
> You
> are running some command (pylint, mypy, unittest, etc.) in that working
> tree. These commands might leave files behind, thus polluting the working

I highly doubt(you could educate me on this
one). At least with python I haven't run into
that. Do you mean *pyc files?

> tree. So successive runs of the same job might see a different state of the
> working tree even when there are no new commits.
>
> It would be better to, after pulling, clone the repo from `GN3_CI_DIR` to
> `CUR_DIR`, and then run the command (pylint, mypy, unittest, etc.) in this
> cloned copy. On the default setting, laminar deletes the contents of `CUR_DIR`
> after the job is done. The cloning is cheap since git tries to hard link when
> possible. See documentation for option -l in the man page of `git clone`.

This sounds more robust. Would never think of
that. I'll edit this to reflect this. Thanks for
pointing this out! Much appreciated!

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Comment by arunisaac** [comment]
Agreed that the "pollution" by pyc files is not likely to cause any
problems. But, the current script leaves behind "side-effects" on the working
tree, and that's making me uneasy. The more robust approach I suggested is
certainly preferable.

**Comment by BonfaceKilz** [comment]
Arun Isaac ***@***.***> anaandika:

> Agreed that the "pollution" by pyc files is not likely to cause any
> problems. But, the current script leaves behind "side-effects" on the working
> tree, and that's making me uneasy. The more robust approach I suggested is
> certainly preferable.

I see! I'll work on hacking on the robust
stuff. I've scheduled this laminar stuff for
Sunday :)

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Comment by arunisaac** [comment]
Another minor nitpick is that the `set -e` can be specified on the shebang
like so:

``` shell
#!/bin/sh -e
```

No big deal, but it does make the script one line shorter! :-P

**Comment by BonfaceKilz** [comment]
Arun Isaac ***@***.***> anaandika:

> Another minor nitpick is that the `set -e` can be specified on the shebang
> like so:
>
> ``` shell
> #!/bin/sh -e
> ```
>
> No big deal, but it does make the script one line shorter! :-P

Wow! I'll tag you on all my PR's for your
reviews. I have lots to learn from you!

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Comment by fredmanglis** [comment]
@arunisaac @BonfaceKilz With the move to using guix, guix-forge and laminar, methinks this issue is obsolete. I'm closing it.

If it is still relevant, please reopen and tag me, and I will migrate it to the gemtext tracker, and close it with a link to the gemtext issue.

**Comment by arunisaac** [comment]
> @arunisaac @BonfaceKilz With the move to using guix, guix-forge and
> laminar, methinks this issue is obsolete.

Yes, that's correct.

> I'm closing it.

Thanks!
