### ISSUE TITLE
Implement biweight midcorrelation in Python without R

### ISSUE THREAD

**Issue by arunisaac** [genenetwork/genenetwork3#25]
The pingouin package supports biweight midcorrelation. See
https://pingouin-stats.org/generated/pingouin.corr.html . We might want to use
it instead of our current R implementation in `gn3/computations/biweight.py`
and `scripts/calculate_biweight.R`. But, currently pingouin doesn't seem to be
packaged for Guix. We'll have to package it first.

**Comment by BonfaceKilz** [comment]
@Alexanderlacuna have a look at that :point_up:

**Comment by BonfaceKilz** [comment]
Hi!

Arun Isaac ***@***.***> anaandika:

> The pingouin package supports biweight midcorrelation. See
> https://pingouin-stats.org/generated/pingouin.corr.html . We might want to use
> it instead of our current R implementation in `gn3/computations/biweight.py`
> and `scripts/calculate_biweight.R`. But, currently pingouin doesn't seem to be
> packaged for Guix. We'll have to package it first.

For packaging, I normally package things first in:
https://git.genenetwork.org/guix-bioinformatics/guix-bioinformatics.git/
before up-streaming... This way, we don't need to
wait for upstream to merge the patch-set. @alex
how about looking at that package? If you think
it's viable, it'd be a good exercise for you in
packaging(python packages are relatively easy to
package).

-- 
Bonface M. K. D4F09EB110177E03C28E2FE1F5BBAE1E0392253F
Free Software Activist
Humble GNU Emacs User | Bearer of scheme-y parens
Curator: <https://upbookclub.com> | Twitter: @BonfaceKilz

**Comment by Alexanderlacuna** [comment]
Cool

**Comment by Alexanderlacuna** [comment]
changes made in this PR: https://github.com/genenetwork/genenetwork3/pull/47

**Comment by fredmanglis** [comment]
@Alexanderlacuna @arunisaac @BonfaceKilz I'm closing this as completed, since the PR mentioned above seems to have been merged.

In case I got that wrong, reopen it and tag me, and I will migrate the issue to the gemtext tracker and close this.
