### ISSUE TITLE
[Feature Request] Command Line Client

### ISSUE THREAD

**Issue by jgarte** [genenetwork/genenetwork3#39]
@pjotrp  @BonfaceKilz @arunisaac @zsloan 

I'm just adding a feature request idea in case we find it to be nice to add later on.

I think this feature might interest scientific researchers who are comfortable with the command line.

I'd love for GeneNetwork to have a nice command line client for doing most if not all the things you can do with the html interface (GN2) and/or the API (GN3). 

[GitHub](https://cli.github.com/) and [GNU MediaGoblin](https://docs.mediagoblin.org/en/master/siteadmin/commandline-upload.html) have one.

GNU MediaGoblin CLI Commands/Client:

https://git.savannah.gnu.org/cgit/mediagoblin.git/tree/mediagoblin/gmg_commands

GNU MediaGoblin has a basic API:

https://git.savannah.gnu.org/cgit/mediagoblin.git/tree/mediagoblin/api

Github Command Line Client:

https://cli.github.com/

**Comment by pjotrp** [comment]
Can we use gemtext instead of the issue tracker?

**Comment by jgarte** [comment]
> Can we use gemtext instead of the issue tracker?

Will move it there, thanks
